# yaml-language-server: $schema=./dependency-sharing-schema.json

foo-bar:
  requiredVersion: 1.0.0
'@bax/foo-bar':
  requiredVersion: 1.0.0
  singleton: true
'@bax-baz/foo-bar2':
  requiredVersion: ^1.2.0
  version: 1.4.0
